### ISSUE TITLE
Configuration for other text editors

### ISSUE THREAD

**Issue by anjayluh** [Lanseuo/revue#5]
Kindly include configuration for any other text editors besides nano

**Comment by Lanseuo** [comment]
Sorry, I don't really understand your question / demand.

I think, you refer to [`nano config.py`](https://github.com/Lanseuo/revue#user-content-installation) in the README.md file. You can use whatever text editor you want (e.g. gedit, Notepad, ...) for editing `config.py`. The configuration is independent of the text editor.

Did I understand that right?
